/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleListItemAuthorAvatar } from './articleListItemAuthorAvatar';
import type { ArticleListItemCommunitySlug } from './articleListItemCommunitySlug';
import type { ArticleListItemLink } from './articleListItemLink';
import type { ArticleListItemMainImageUrl } from './articleListItemMainImageUrl';
import type { ArticleListItemSubtitle } from './articleListItemSubtitle';

/**
 * Simplified schema for article lists (without full content)
 */
export interface ArticleListItem {
  id: number;
  title: string;
  subtitle?: ArticleListItemSubtitle;
  main_image_url?: ArticleListItemMainImageUrl;
  content_preview: string;
  link?: ArticleListItemLink;
  author_username: string;
  author_display_name: string;
  author_avatar?: ArticleListItemAuthorAvatar;
  community_id: number;
  community_name: string;
  community_slug?: ArticleListItemCommunitySlug;
  is_published: boolean;
  view_count?: number;
  like_count?: number;
  comment_count?: number;
  is_author?: boolean;
  is_bookmarked?: boolean;
  created_at: string;
  updated_at: string;
}
