/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleUpdateSchemaAuthorName } from './articleUpdateSchemaAuthorName';
import type { ArticleUpdateSchemaContent } from './articleUpdateSchemaContent';
import type { ArticleUpdateSchemaIsPublished } from './articleUpdateSchemaIsPublished';
import type { ArticleUpdateSchemaLink } from './articleUpdateSchemaLink';
import type { ArticleUpdateSchemaSubtitle } from './articleUpdateSchemaSubtitle';
import type { ArticleUpdateSchemaTitle } from './articleUpdateSchemaTitle';

/**
 * Schema for updating an article
 */
export interface ArticleUpdateSchema {
  title?: ArticleUpdateSchemaTitle;
  subtitle?: ArticleUpdateSchemaSubtitle;
  content?: ArticleUpdateSchemaContent;
  link?: ArticleUpdateSchemaLink;
  author_name?: ArticleUpdateSchemaAuthorName;
  is_published?: ArticleUpdateSchemaIsPublished;
}
