/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleDetailsAuthorAvatar } from './articleDetailsAuthorAvatar';
import type { ArticleDetailsAuthorName } from './articleDetailsAuthorName';
import type { ArticleDetailsCommunityAvatar } from './articleDetailsCommunityAvatar';
import type { ArticleDetailsCommunitySlug } from './articleDetailsCommunitySlug';
import type { ArticleDetailsLink } from './articleDetailsLink';
import type { ArticleDetailsMainImageUrl } from './articleDetailsMainImageUrl';
import type { ArticleDetailsSubtitle } from './articleDetailsSubtitle';
import type { ArticleDetailsUserReactions } from './articleDetailsUserReactions';

/**
 * Complete article schema used across all endpoints
 */
export interface ArticleDetails {
  id: number;
  title: string;
  subtitle?: ArticleDetailsSubtitle;
  main_image_url?: ArticleDetailsMainImageUrl;
  link?: ArticleDetailsLink;
  content: string;
  author_name?: ArticleDetailsAuthorName;
  author_username: string;
  author_display_name: string;
  author_avatar?: ArticleDetailsAuthorAvatar;
  author_aura: number;
  community_id: number;
  community_name: string;
  community_slug?: ArticleDetailsCommunitySlug;
  community_avatar?: ArticleDetailsCommunityAvatar;
  is_published: boolean;
  view_count?: number;
  like_count?: number;
  dislike_count?: number;
  share_count?: number;
  comment_count?: number;
  is_author?: boolean;
  user_reactions?: ArticleDetailsUserReactions;
  is_bookmarked?: boolean;
  created_at: string;
  updated_at: string;
}
