/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { BookmarkFolderQueryParamsAccessLevel } from './bookmarkFolderQueryParamsAccessLevel';
import type { BookmarkFolderQueryParamsCommunityId } from './bookmarkFolderQueryParamsCommunityId';
import type { BookmarkFolderQueryParamsContentType } from './bookmarkFolderQueryParamsContentType';
import type { BookmarkFolderQueryParamsIsTodoFolder } from './bookmarkFolderQueryParamsIsTodoFolder';
import type { BookmarkFolderQueryParamsOrdering } from './bookmarkFolderQueryParamsOrdering';
import type { BookmarkFolderQueryParamsPage } from './bookmarkFolderQueryParamsPage';
import type { BookmarkFolderQueryParamsPageSize } from './bookmarkFolderQueryParamsPageSize';
import type { BookmarkFolderQueryParamsSearch } from './bookmarkFolderQueryParamsSearch';

/**
 * Query parameters for filtering bookmark folders
 */
export interface BookmarkFolderQueryParams {
  page?: BookmarkFolderQueryParamsPage;
  page_size?: BookmarkFolderQueryParamsPageSize;
  access_level?: BookmarkFolderQueryParamsAccessLevel;
  content_type?: BookmarkFolderQueryParamsContentType;
  is_todo_folder?: BookmarkFolderQueryParamsIsTodoFolder;
  search?: BookmarkFolderQueryParamsSearch;
  community_id?: BookmarkFolderQueryParamsCommunityId;
  ordering?: BookmarkFolderQueryParamsOrdering;
}
