/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { BookmarkFolderCreateSchemaColor } from './bookmarkFolderCreateSchemaColor';
import type { BookmarkFolderCreateSchemaCommunityId } from './bookmarkFolderCreateSchemaCommunityId';
import type { BookmarkFolderCreateSchemaContentType } from './bookmarkFolderCreateSchemaContentType';
import type { BookmarkFolderCreateSchemaDescription } from './bookmarkFolderCreateSchemaDescription';
import type { BookmarkFolderCreateSchemaPrice } from './bookmarkFolderCreateSchemaPrice';

/**
 * Schema for creating a bookmark folder
 */
export interface BookmarkFolderCreateSchema {
  name: string;
  description?: BookmarkFolderCreateSchemaDescription;
  color?: BookmarkFolderCreateSchemaColor;
  access_level?: string;
  price?: BookmarkFolderCreateSchemaPrice;
  is_todo_folder?: boolean;
  content_type?: BookmarkFolderCreateSchemaContentType;
  community_id?: BookmarkFolderCreateSchemaCommunityId;
}
