/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { BookmarkFolderDetailsSchema } from './bookmarkFolderDetailsSchema';
import type { PaginationSchema } from './paginationSchema';

/**
 * Response schema for paginated bookmark folders list
 */
export interface BookmarkFoldersListResponseSchema {
  folders: BookmarkFolderDetailsSchema[];
  pagination: PaginationSchema;
}
