/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { BulkNotificationPreferenceUpdateInEmailEnabled } from './bulkNotificationPreferenceUpdateInEmailEnabled';
import type { BulkNotificationPreferenceUpdateInInAppEnabled } from './bulkNotificationPreferenceUpdateInInAppEnabled';
import type { BulkNotificationPreferenceUpdateInPushEnabled } from './bulkNotificationPreferenceUpdateInPushEnabled';

export interface BulkNotificationPreferenceUpdateIn {
  push_enabled?: BulkNotificationPreferenceUpdateInPushEnabled;
  email_enabled?: BulkNotificationPreferenceUpdateInEmailEnabled;
  in_app_enabled?: BulkNotificationPreferenceUpdateInInAppEnabled;
}
