/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { ChatUsersFiltersSchemaSearch } from './chatUsersFiltersSchemaSearch';
import type { ChatUsersFiltersSchemaUnreadOnly } from './chatUsersFiltersSchemaUnreadOnly';

export interface ChatUsersFiltersSchema {
  search?: ChatUsersFiltersSchemaSearch;
  community_id: number;
  unread_only?: ChatUsersFiltersSchemaUnreadOnly;
  page?: number;
  per_page?: number;
}
