/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { ChatUserItemSchemaAvatar } from './chatUserItemSchemaAvatar';
import type { ChatUserItemSchemaChatId } from './chatUserItemSchemaChatId';
import type { ChatUserItemSchemaLastMessage } from './chatUserItemSchemaLastMessage';
import type { ChatUserItemSchemaLastSeen } from './chatUserItemSchemaLastSeen';

export interface ChatUserItemSchema {
  user_id: number;
  username: string;
  display_name: string;
  avatar?: ChatUserItemSchemaAvatar;
  is_online: boolean;
  last_seen?: ChatUserItemSchemaLastSeen;
  is_mentor: boolean;
  message_rate: number;
  role: string;
  chat_id?: ChatUserItemSchemaChatId;
  last_message?: ChatUserItemSchemaLastMessage;
  unread_count?: number;
  has_chatted?: boolean;
}
