/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityUpdateSchemaDescription } from './communityUpdateSchemaDescription';
import type { CommunityUpdateSchemaRules } from './communityUpdateSchemaRules';

/**
 * Schema for updating community details
 */
export interface CommunityUpdateSchema {
  description?: CommunityUpdateSchemaDescription;
  rules?: CommunityUpdateSchemaRules;
}
