/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityListQueryCategoryId } from './communityListQueryCategoryId';
import type { CommunityListQueryCommunityType } from './communityListQueryCommunityType';
import type { CommunityListQueryCreatorId } from './communityListQueryCreatorId';
import type { CommunityListQueryMyRole } from './communityListQueryMyRole';
import type { CommunityListQueryMyStatus } from './communityListQueryMyStatus';
import type { CommunityListQuerySearch } from './communityListQuerySearch';
import type { CommunityListQueryTag } from './communityListQueryTag';

export interface CommunityListQuery {
  page?: number;
  page_size?: number;
  search?: CommunityListQuerySearch;
  category_id?: CommunityListQueryCategoryId;
  community_type?: CommunityListQueryCommunityType;
  tag?: CommunityListQueryTag;
  creator_id?: CommunityListQueryCreatorId;
  my_communities?: boolean;
  my_role?: CommunityListQueryMyRole;
  my_status?: CommunityListQueryMyStatus;
  sort_by?: string;
  order?: string;
  include_inactive?: boolean;
}
