/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { CommunitySchemaCategory } from './communitySchemaCategory';
import type { CommunitySchemaCreator } from './communitySchemaCreator';
import type { CommunitySchemaTagsItem } from './communitySchemaTagsItem';
import type { CommunitySchemaUserCanJoin } from './communitySchemaUserCanJoin';
import type { CommunitySchemaUserCanPost } from './communitySchemaUserCanPost';
import type { CommunitySchemaUserMembership } from './communitySchemaUserMembership';

export interface CommunitySchema {
  id: number;
  name: string;
  description: string;
  community_type: string;
  creator: CommunitySchemaCreator;
  category: CommunitySchemaCategory;
  tags?: CommunitySchemaTagsItem[];
  member_count: number;
  poll_count: number;
  requires_aura_to_join: number;
  requires_aura_to_post: number;
  created_at: string;
  updated_at: string;
  is_active: boolean;
  user_membership?: CommunitySchemaUserMembership;
  user_can_join?: CommunitySchemaUserCanJoin;
  user_can_post?: CommunitySchemaUserCanPost;
}
