/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

/**
 * Enum for comment sorting options
 */
export type CommentSortEnum = (typeof CommentSortEnum)[keyof typeof CommentSortEnum];

 
export const CommentSortEnum = {
  newest: 'newest',
  oldest: 'oldest',
  most_liked: 'most_liked',
  most_replies: 'most_replies',
} as const;
