/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { MembershipDetailsSchema } from './membershipDetailsSchema';

export type CommunityDetailsMembershipDetails = MembershipDetailsSchema | null;
