/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { CommentOut } from './commentOut';
import type { CommentResponseCommentId } from './commentResponseCommentId';

/**
 * Standard response for comment operations
 */
export interface CommentResponse {
  success: boolean;
  message: string;
  comment_id?: CommentResponseCommentId;
  data: CommentOut;
}
