/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryResponseSchema } from './categoryResponseSchema';
import type { TagResponseSchema } from './tagResponseSchema';

export interface CommunityResponseSchema {
  id: number;
  name: string;
  description: string;
  community_type: string;
  creator_id: number;
  category: CategoryResponseSchema;
  tags: TagResponseSchema[];
  member_count: number;
  poll_count: number;
  requires_aura_to_join: number;
  requires_aura_to_post: number;
  created_at: string;
  is_active: boolean;
}
