/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

/**
 * Enum for comment search types
 */
export type CommentSearchTypeEnum =
  (typeof CommentSearchTypeEnum)[keyof typeof CommentSearchTypeEnum];

 
export const CommentSearchTypeEnum = {
  all: 'all',
  content: 'content',
  author: 'author',
  media: 'media',
  links: 'links',
} as const;
