/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityDetails } from './communityDetails';
import type { CommunityListResponseFiltersApplied } from './communityListResponseFiltersApplied';
import type { CommunityListResponsePagination } from './communityListResponsePagination';

export interface CommunityListResponse {
  communities: CommunityDetails[];
  pagination: CommunityListResponsePagination;
  filters_applied: CommunityListResponseFiltersApplied;
}
