/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export type CommunityMembershipSchemaAction =
  (typeof CommunityMembershipSchemaAction)[keyof typeof CommunityMembershipSchemaAction];

export const CommunityMembershipSchemaAction = {
  join: 'join',
  leave: 'leave',
} as const;
