/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { CompleteGoogleRegistrationSchemaDisplayName } from './completeGoogleRegistrationSchemaDisplayName';

export interface CompleteGoogleRegistrationSchema {
  google_id: string;
  username: string;
  display_name?: CompleteGoogleRegistrationSchemaDisplayName;
}
