/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

/**
 * Enum for valid content types
 */
export type ContentTypeEnum = (typeof ContentTypeEnum)[keyof typeof ContentTypeEnum];

export const ContentTypeEnum = {
  Poll: 'Poll',
  GenericComment: 'GenericComment',
} as const;
