/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTimelineItemSchemaCallDuration } from './createTimelineItemSchemaCallDuration';
import type { CreateTimelineItemSchemaCallStatus } from './createTimelineItemSchemaCallStatus';
import type { CreateTimelineItemSchemaChatId } from './createTimelineItemSchemaChatId';
import type { CreateTimelineItemSchemaCommunityId } from './createTimelineItemSchemaCommunityId';
import type { CreateTimelineItemSchemaContent } from './createTimelineItemSchemaContent';
import type { CreateTimelineItemSchemaServiceItemId } from './createTimelineItemSchemaServiceItemId';

export interface CreateTimelineItemSchema {
  chat_id?: CreateTimelineItemSchemaChatId;
  community_id?: CreateTimelineItemSchemaCommunityId;
  item_type: string;
  content?: CreateTimelineItemSchemaContent;
  service_item_id?: CreateTimelineItemSchemaServiceItemId;
  call_duration?: CreateTimelineItemSchemaCallDuration;
  call_status?: CreateTimelineItemSchemaCallStatus;
}
