/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { CreateServiceSchemaMaxMessagesADay } from './createServiceSchemaMaxMessagesADay';
import type { CreateServiceSchemaReplyTime } from './createServiceSchemaReplyTime';

export interface CreateServiceSchema {
  community_slug: string;
  service_type: string;
  name: string;
  description: string;
  price: number;
  duration_minutes?: number;
  is_duration_based?: boolean;
  status?: string;
  attachments_required?: boolean;
  max_messages_a_day?: CreateServiceSchemaMaxMessagesADay;
  reply_time?: CreateServiceSchemaReplyTime;
}
