/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export interface CreateChatResponseSchema {
  chat_id: string;
  mentor_id: number;
  mentor_username: string;
  mentor_display_name: string;
  community_id: number;
  created: boolean;
  message: string;
}
