/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for FCM response
 */
export interface FCMResponse {
  success: boolean;
  message: string;
}
