/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { GoogleDataSchema } from './googleDataSchema';
import type { ProfileDetailsSchema } from './profileDetailsSchema';

export interface GoogleSignInResponseSchema {
  success: boolean;
  token?: string;
  user?: ProfileDetailsSchema;
  requires_completion?: boolean;
  google_data?: GoogleDataSchema;
  error?: string;
}
