/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export type KeyopollsPollsApiGeneralListPollsParams = {
  /**
   * Filter by community ID
   */
  community_id?: number | null;
  /**
   * Filter by community slug
   */
  community_slug?: string | null;
  /**
   * Filter by folder ID (for lists)
   */
  folder_id?: number | null;
  /**
   * Filter by category ID (1 = for-you feed)
   */
  category_id?: number | null;
  /**
   * Filter by poll type (single, multiple, ranking)
   */
  poll_type?: string | null;
  /**
   * Filter by status (active, closed, archived, draft, pending_moderation, rejected). Can provide multiple values.
   */
  status?: string[] | null;
  /**
   * Filter by author profile ID
   */
  author_id?: number | null;
  /**
   * Filter by multiple tag slugs (AND operation)
   */
  tags?: string[] | null;
  /**
   * Search in poll title and description
   */
  search?: string | null;
  /**
   * Show only user's polls
   */
  my_polls?: boolean;
  /**
   * Show polls from user's communities only
   */
  my_communities?: boolean;
  /**
   * Filter by voted status (true/false)
   */
  voted?: boolean | null;
  /**
   * Page number
   */
  page?: number;
  /**
   * Items per page (max 100)
   */
  page_size?: number;
  /**
   * Sort: newest, oldest, most_votes, most_popular, trending
   */
  sort?: string;
  /**
   * Include expired polls
   */
  include_expired?: boolean;
  /**
   * Minimum aura requirement
   */
  min_aura?: number | null;
};
