/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export type KeyopollsTransactionsApiGetUserTransactionsParams = {
  transaction_type?: string | null;
  status?: string | null;
  min_amount?: number | null;
  max_amount?: number | null;
  date_from?: string | null;
  date_to?: string | null;
  payment_method?: string | null;
  search?: string | null;
  credits_only?: boolean | null;
  debits_only?: boolean | null;
  page?: number;
  per_page?: number;
  order_by?: string;
};
