/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { CreateServiceSchema } from './createServiceSchema';

export type KeyopollsChatsApiServicesCreateServiceBody = {
  attachments?: Blob[];
  preview_image?: Blob;
  data: CreateServiceSchema;
};
