/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export type KeyopollsCommonApiTagsGetTagsListParams = {
  search?: string | null;
  community_id?: number | null;
  community_slug?: string | null;
  page?: number;
  per_page?: number;
  order_by?: string;
};
