/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export type KeyopollsCommunitiesApiGeneralListCommunitiesParams = {
  page?: number;
  page_size?: number;
  search?: string | null;
  category_id?: number | null;
  community_type?: string | null;
  tag?: string | null;
  creator_id?: number | null;
  my_communities?: boolean;
  my_role?: string | null;
  my_status?: string | null;
  sort_by?: string;
  order?: string;
  include_inactive?: boolean;
};
