/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export type KeyopollsCommonApiTodoListTodosParams = {
  page?: number | null;
  page_size?: number | null;
  completed?: boolean | null;
  overdue?: boolean | null;
  search?: string | null;
  ordering?: string | null;
};
