/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export type KeyopollsCommonApiBookmarkGetUserBookmarksParams = {
  folder_id?: number;
  content_type?: string;
  page?: number;
  page_size?: number;
};
