/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export type KeyopollsNotificationsApiFcmTestSendCommunityNotificationParams = {
  /**
   * Community ID
   */
  community_id: number;
  /**
   * Notification title
   */
  title: string;
  /**
   * Notification body
   */
  body: string;
  /**
   * Notification type
   */
  notification_type?: string | null;
};
