/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export type KeyopollsCommonApiBookmarkGetBookmarkFoldersParams = {
  page?: number | null;
  page_size?: number | null;
  access_level?: string | null;
  content_type?: string | null;
  is_todo_folder?: boolean | null;
  search?: string | null;
  community_id?: number | null;
  ordering?: string | null;
};
