/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export type KeyopollsCommentsApiGetCommentsParams = {
  page?: number;
  page_size?: number;
  sort?: 'newest' | 'oldest' | 'most_liked' | 'most_replies';
};
