/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export type KeyopollsNotificationsApiGeneralGetNotificationsParams = {
  /**
   * Page number
   * @minimum 1
   */
  page?: number;
  /**
   * Items per page
   * @minimum 1
   * @maximum 100
   */
  page_size?: number;
  /**
   * Filter by notification type
   */
  notification_type?: string | null;
  /**
   * Filter by priority (low, normal, high, urgent)
   */
  priority?: string | null;
  /**
   * Filter by read status
   */
  is_read?: boolean | null;
  /**
   * Filter by clicked status
   */
  is_clicked?: boolean | null;
  /**
   * Filter by specific actor ID
   */
  actor_id?: number | null;
  /**
   * Filter by target type (poll, comment, profile, community)
   */
  target_type?: string | null;
  /**
   * Filter by specific target ID
   */
  target_id?: number | null;
  /**
   * Filter from date (ISO format: 2024-01-01)
   */
  date_from?: string | null;
  /**
   * Filter to date (ISO format: 2024-01-31)
   */
  date_to?: string | null;
  /**
   * Filter by days ago (e.g., 7 for last week)
   */
  days_ago?: number | null;
  /**
   * Search in title and message
   */
  search?: string | null;
  /**
   * Show only unread notifications
   */
  unread_only?: boolean;
  /**
   * Show only recent notifications (last 24h)
   */
  recent_only?: boolean;
  /**
   * Exclude expired notifications
   */
  exclude_expired?: boolean;
  /**
   * Sort by: created_at, read_at, priority
   */
  sort_by?: string;
  /**
   * Sort order: asc or desc
   */
  sort_order?: string;
  /**
   * Include summary statistics
   */
  include_summary?: boolean;
};
