/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateServiceSchema } from './updateServiceSchema';

export type KeyopollsChatsApiServicesUpdateServiceBody = {
  attachments?: Blob[];
  preview_image?: Blob;
  data: UpdateServiceSchema;
};
