/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { LinkSchemaDescription } from './linkSchemaDescription';
import type { LinkSchemaDomain } from './linkSchemaDomain';
import type { LinkSchemaImageUrl } from './linkSchemaImageUrl';
import type { LinkSchemaTitle } from './linkSchemaTitle';

/**
 * Schema for link attachments
 */
export interface LinkSchema {
  id: number;
  url: string;
  display_text: string;
  domain?: LinkSchemaDomain;
  title?: LinkSchemaTitle;
  description?: LinkSchemaDescription;
  image_url?: LinkSchemaImageUrl;
  is_active: boolean;
  click_count: number;
  created_at: string;
}
