/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { ManagePollInListSchemaNote } from './managePollInListSchemaNote';
import type { ManagePollInListSchemaOrder } from './managePollInListSchemaOrder';

export interface ManagePollInListSchema {
  poll_id: number;
  action: string;
  order?: ManagePollInListSchemaOrder;
  note?: ManagePollInListSchemaNote;
}
