/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { MentorDetailsSchemaAvatar } from './mentorDetailsSchemaAvatar';
import type { MentorDetailsSchemaLastSeen } from './mentorDetailsSchemaLastSeen';

export interface MentorDetailsSchema {
  id: number;
  username: string;
  display_name: string;
  avatar?: MentorDetailsSchemaAvatar;
  is_online: boolean;
  last_seen?: MentorDetailsSchemaLastSeen;
}
