/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for a simple message response
 */
export interface Message {
  message: string;
}
