/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationSchemaActorInfo } from './notificationSchemaActorInfo';
import type { NotificationSchemaClickUrl } from './notificationSchemaClickUrl';
import type { NotificationSchemaClickedAt } from './notificationSchemaClickedAt';
import type { NotificationSchemaDeepLinkData } from './notificationSchemaDeepLinkData';
import type { NotificationSchemaExtraData } from './notificationSchemaExtraData';
import type { NotificationSchemaReadAt } from './notificationSchemaReadAt';
import type { NotificationSchemaTargetInfo } from './notificationSchemaTargetInfo';

/**
 * Schema for individual notification response
 */
export interface NotificationSchema {
  id: number;
  notification_type: string;
  title: string;
  message: string;
  priority: string;
  click_url?: NotificationSchemaClickUrl;
  deep_link_data?: NotificationSchemaDeepLinkData;
  is_read: boolean;
  is_clicked: boolean;
  actor_info?: NotificationSchemaActorInfo;
  target_info?: NotificationSchemaTargetInfo;
  extra_data?: NotificationSchemaExtraData;
  created_at: string;
  read_at?: NotificationSchemaReadAt;
  clicked_at?: NotificationSchemaClickedAt;
  push_sent?: boolean;
  email_sent?: boolean;
}
