/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationSummaryResponseUnreadByPriority } from './notificationSummaryResponseUnreadByPriority';
import type { NotificationSummaryResponseUnreadByType } from './notificationSummaryResponseUnreadByType';

/**
 * Schema for notification summary statistics
 */
export interface NotificationSummaryResponse {
  total_count: number;
  unread_count: number;
  recent_count: number;
  recent_unread_count: number;
  unread_by_type: NotificationSummaryResponseUnreadByType;
  unread_by_priority: NotificationSummaryResponseUnreadByPriority;
  read_percentage: number;
}
