/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for updating notification preferences
 */
export interface NotificationPreferenceUpdateIn {
  push_enabled: boolean;
  email_enabled: boolean;
  in_app_enabled: boolean;
  is_enabled: boolean;
}
