/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationSummarySchemaUnreadByType } from './notificationSummarySchemaUnreadByType';

/**
 * Schema for notification summary statistics
 */
export interface NotificationSummarySchema {
  total_count: number;
  unread_count: number;
  recent_count: number;
  unread_by_type: NotificationSummarySchemaUnreadByType;
}
