/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { CommentSearchResultOut } from './commentSearchResultOut';
import type { PaginatedCommentSearchResponseProfileFilter } from './paginatedCommentSearchResponseProfileFilter';
import type { PaginatedCommentSearchResponseSearchQuery } from './paginatedCommentSearchResponseSearchQuery';
import type { PaginatedCommentSearchResponseSearchType } from './paginatedCommentSearchResponseSearchType';

/**
 * Paginated response for comment search results
 */
export interface PaginatedCommentSearchResponse {
  items: CommentSearchResultOut[];
  total: number;
  page: number;
  pages: number;
  page_size: number;
  has_next: boolean;
  has_previous: boolean;
  search_query?: PaginatedCommentSearchResponseSearchQuery;
  search_type?: PaginatedCommentSearchResponseSearchType;
  profile_filter?: PaginatedCommentSearchResponseProfileFilter;
  include_poll_content?: boolean;
  total_time_ms: number;
}
