/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { CommentOut } from './commentOut';

/**
 * Paginated response for comment lists
 */
export interface PaginatedCommentResponse {
  items: CommentOut[];
  total: number;
  page: number;
  pages: number;
  page_size: number;
  has_next: boolean;
  has_previous: boolean;
}
