/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { PaginationSchemaNextPage } from './paginationSchemaNextPage';
import type { PaginationSchemaPreviousPage } from './paginationSchemaPreviousPage';

export interface PaginationSchema {
  current_page: number;
  total_pages: number;
  total_count: number;
  has_next: boolean;
  has_previous: boolean;
  page_size: number;
  next_page?: PaginationSchemaNextPage;
  previous_page?: PaginationSchemaPreviousPage;
}
