/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { CountryViewsSchema } from './countryViewsSchema';
import type { HourlyViewsSchema } from './hourlyViewsSchema';
import type { PollDataSchema } from './pollDataSchema';

export interface PollInsightsSchema {
  poll: PollDataSchema;
  first_48_hours_data: HourlyViewsSchema[];
  top_countries: CountryViewsSchema[];
  total_impressions: number;
  unique_profiles: number;
  anonymous_impressions: number;
  authenticated_impressions: number;
}
