/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { PollListCreateSchemaDescription } from './pollListCreateSchemaDescription';
import type { PollListCreateSchemaIsCollaborative } from './pollListCreateSchemaIsCollaborative';
import type { PollListCreateSchemaListType } from './pollListCreateSchemaListType';
import type { PollListCreateSchemaMaxPolls } from './pollListCreateSchemaMaxPolls';
import type { PollListCreateSchemaParentId } from './pollListCreateSchemaParentId';
import type { PollListCreateSchemaVisibility } from './pollListCreateSchemaVisibility';

export interface PollListCreateSchema {
  title: string;
  description?: PollListCreateSchemaDescription;
  community_slug: string;
  parent_id?: PollListCreateSchemaParentId;
  list_type?: PollListCreateSchemaListType;
  visibility?: PollListCreateSchemaVisibility;
  is_collaborative?: PollListCreateSchemaIsCollaborative;
  max_polls?: PollListCreateSchemaMaxPolls;
}
