/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { PollListCommunitySchemaAvatarUrl } from './pollListCommunitySchemaAvatarUrl';
import type { PollListCommunitySchemaSlug } from './pollListCommunitySchemaSlug';

export interface PollListCommunitySchema {
  id: number;
  name: string;
  slug?: PollListCommunitySchemaSlug;
  avatar_url?: PollListCommunitySchemaAvatarUrl;
}
