/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { PollUpdateSchemaExplanation } from './pollUpdateSchemaExplanation';
import type { PollUpdateSchemaTags } from './pollUpdateSchemaTags';

export interface PollUpdateSchema {
  title: string;
  description?: string;
  tags?: PollUpdateSchemaTags;
  explanation?: PollUpdateSchemaExplanation;
}
