/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { AuthorSchema } from './authorSchema';

/**
 * Schema for poll content when included in comment search results
 */
export interface PollContentSchema {
  id: number;
  title: string;
  description: string;
  poll_type: string;
  author_info: AuthorSchema;
  total_votes: number;
  option_count: number;
}
