/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { PollOptionSchema } from './pollOptionSchema';
import type { PollSchemaExpiresAt } from './pollSchemaExpiresAt';
import type { PollSchemaMaxChoices } from './pollSchemaMaxChoices';

/**
 * Common poll schema used across all endpoints
 */
export interface PollSchema {
  id: number;
  title: string;
  description: string;
  poll_type: string;
  status: string;
  author_username: string;
  author_display_name: string;
  author_aura: number;
  community_id: number;
  community_name: string;
  allow_multiple_votes: boolean;
  max_choices?: PollSchemaMaxChoices;
  requires_aura: number;
  is_pinned: boolean;
  expires_at?: PollSchemaExpiresAt;
  is_active: boolean;
  is_expired: boolean;
  total_votes: number;
  total_voters: number;
  option_count: number;
  view_count: number;
  comment_count: number;
  options: PollOptionSchema[];
  user_can_vote?: boolean;
  user_has_voted?: boolean;
  is_author?: boolean;
  created_at: string;
  updated_at: string;
}
