/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { MultipleChoiceStatsSchema } from './multipleChoiceStatsSchema';
import type { PollDetailsCommunityAvatar } from './pollDetailsCommunityAvatar';
import type { PollDetailsCorrectAnswerStats } from './pollDetailsCorrectAnswerStats';
import type { PollDetailsExpiresAt } from './pollDetailsExpiresAt';
import type { PollDetailsImageUrl } from './pollDetailsImageUrl';
import type { PollDetailsMaxChoices } from './pollDetailsMaxChoices';
import type { PollDetailsUserReactions } from './pollDetailsUserReactions';
import type { PollDetailsUserTextResponse } from './pollDetailsUserTextResponse';
import type { PollOptionSchema } from './pollOptionSchema';
import type { TextResponseSchema } from './textResponseSchema';
import type { UserVoteDetails } from './userVoteDetails';

/**
 * Common poll schema used across all endpoints
 */
export interface PollDetails {
  id: number;
  title: string;
  description: string;
  image_url?: PollDetailsImageUrl;
  poll_type: string;
  status: string;
  author_username: string;
  author_display_name: string;
  author_aura: number;
  community_id: number;
  community_name: string;
  community_avatar?: PollDetailsCommunityAvatar;
  allow_multiple_votes: boolean;
  max_choices?: PollDetailsMaxChoices;
  requires_aura: number;
  is_pinned: boolean;
  has_correct_answer: boolean;
  correct_answer_stats?: PollDetailsCorrectAnswerStats;
  expires_at?: PollDetailsExpiresAt;
  is_active: boolean;
  is_expired: boolean;
  total_votes: number;
  total_voters: number;
  option_count: number;
  view_count: number;
  comment_count: number;
  like_count: number;
  dislike_count: number;
  share_count: number;
  impressions_count: number;
  options?: PollOptionSchema[];
  text_responses?: TextResponseSchema[];
  multiple_choice_stats?: MultipleChoiceStatsSchema[];
  user_can_vote?: boolean;
  user_has_voted?: boolean;
  is_author?: boolean;
  show_results?: boolean;
  user_reactions?: PollDetailsUserReactions;
  is_bookmarked?: boolean;
  user_votes?: UserVoteDetails[];
  user_text_response?: PollDetailsUserTextResponse;
  created_at: string;
  updated_at: string;
}
