/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { PollOptionSchemaBestRank } from './pollOptionSchemaBestRank';
import type { PollOptionSchemaBestRankPercentage } from './pollOptionSchemaBestRankPercentage';
import type { PollOptionSchemaImageUrl } from './pollOptionSchemaImageUrl';
import type { PollOptionSchemaRankBreakdown } from './pollOptionSchemaRankBreakdown';

export interface PollOptionSchema {
  id: number;
  text: string;
  image_url?: PollOptionSchemaImageUrl;
  order: number;
  vote_count: number;
  vote_percentage: number;
  is_correct?: boolean;
  best_rank?: PollOptionSchemaBestRank;
  best_rank_percentage?: PollOptionSchemaBestRankPercentage;
  rank_breakdown?: PollOptionSchemaRankBreakdown;
}
