/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { PollListQueryParamsCommunityId } from './pollListQueryParamsCommunityId';
import type { PollListQueryParamsCommunitySlug } from './pollListQueryParamsCommunitySlug';
import type { PollListQueryParamsHierarchicalOrder } from './pollListQueryParamsHierarchicalOrder';
import type { PollListQueryParamsIsCollaborative } from './pollListQueryParamsIsCollaborative';
import type { PollListQueryParamsIsFeatured } from './pollListQueryParamsIsFeatured';
import type { PollListQueryParamsListType } from './pollListQueryParamsListType';
import type { PollListQueryParamsMaxDepth } from './pollListQueryParamsMaxDepth';
import type { PollListQueryParamsOrdering } from './pollListQueryParamsOrdering';
import type { PollListQueryParamsOwnerOnly } from './pollListQueryParamsOwnerOnly';
import type { PollListQueryParamsPage } from './pollListQueryParamsPage';
import type { PollListQueryParamsPageSize } from './pollListQueryParamsPageSize';
import type { PollListQueryParamsParentId } from './pollListQueryParamsParentId';
import type { PollListQueryParamsSearch } from './pollListQueryParamsSearch';
import type { PollListQueryParamsVisibility } from './pollListQueryParamsVisibility';

export interface PollListQueryParams {
  page?: PollListQueryParamsPage;
  page_size?: PollListQueryParamsPageSize;
  list_type?: PollListQueryParamsListType;
  visibility?: PollListQueryParamsVisibility;
  community_id?: PollListQueryParamsCommunityId;
  community_slug?: PollListQueryParamsCommunitySlug;
  parent_id?: PollListQueryParamsParentId;
  owner_only?: PollListQueryParamsOwnerOnly;
  is_collaborative?: PollListQueryParamsIsCollaborative;
  is_featured?: PollListQueryParamsIsFeatured;
  max_depth?: PollListQueryParamsMaxDepth;
  search?: PollListQueryParamsSearch;
  ordering?: PollListQueryParamsOrdering;
  hierarchical_order?: PollListQueryParamsHierarchicalOrder;
}
