/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export interface PollDataSchema {
  title: string;
  description: string;
  poll_type: string;
  author: string;
  username: string;
  date: string;
  views: string;
  likes: number;
  total_votes: number;
  total_voters: number;
  option_count: number;
  bookmarks: number;
  comments: number;
  shares: number;
  total_aura: number;
}
