/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { PollListUpdateSchemaDescription } from './pollListUpdateSchemaDescription';
import type { PollListUpdateSchemaIsCollaborative } from './pollListUpdateSchemaIsCollaborative';
import type { PollListUpdateSchemaIsFeatured } from './pollListUpdateSchemaIsFeatured';
import type { PollListUpdateSchemaMaxPolls } from './pollListUpdateSchemaMaxPolls';
import type { PollListUpdateSchemaOrder } from './pollListUpdateSchemaOrder';
import type { PollListUpdateSchemaParentId } from './pollListUpdateSchemaParentId';
import type { PollListUpdateSchemaTitle } from './pollListUpdateSchemaTitle';
import type { PollListUpdateSchemaVisibility } from './pollListUpdateSchemaVisibility';

export interface PollListUpdateSchema {
  title?: PollListUpdateSchemaTitle;
  description?: PollListUpdateSchemaDescription;
  visibility?: PollListUpdateSchemaVisibility;
  is_collaborative?: PollListUpdateSchemaIsCollaborative;
  max_polls?: PollListUpdateSchemaMaxPolls;
  is_featured?: PollListUpdateSchemaIsFeatured;
  parent_id?: PollListUpdateSchemaParentId;
  order?: PollListUpdateSchemaOrder;
}
