/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export interface PollOptionCreateSchema {
  text?: string;
  order: number;
  is_correct?: boolean;
}
