/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { PaginationSchema } from './paginationSchema';
import type { PollListDetailsSchema } from './pollListDetailsSchema';
import type { PollListsListResponseSchemaHierarchy } from './pollListsListResponseSchemaHierarchy';

export interface PollListsListResponseSchema {
  lists: PollListDetailsSchema[];
  pagination: PaginationSchema;
  hierarchy?: PollListsListResponseSchemaHierarchy;
}
