/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { ProfileDetailsSchemaAbout } from './profileDetailsSchemaAbout';
import type { ProfileDetailsSchemaAvatar } from './profileDetailsSchemaAvatar';
import type { ProfileDetailsSchemaBanner } from './profileDetailsSchemaBanner';
import type { ProfileDetailsSchemaIsOwner } from './profileDetailsSchemaIsOwner';

export interface ProfileDetailsSchema {
  id: number;
  username: string;
  display_name: string;
  about?: ProfileDetailsSchemaAbout;
  avatar?: ProfileDetailsSchemaAvatar;
  banner?: ProfileDetailsSchemaBanner;
  email: string;
  aura_polls: number;
  aura_comments: number;
  total_aura: number;
  is_email_verified: boolean;
  created_at: string;
  is_owner?: ProfileDetailsSchemaIsOwner;
}
