/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export type ReactionRequestReactionType =
  (typeof ReactionRequestReactionType)[keyof typeof ReactionRequestReactionType];

 
export const ReactionRequestReactionType = {
  like: 'like',
  dislike: 'dislike',
} as const;
