/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { RegisterDeviceInDeviceInfoAnyOf } from './registerDeviceInDeviceInfoAnyOf';

export type RegisterDeviceInDeviceInfo = RegisterDeviceInDeviceInfoAnyOf | null;
