/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export interface ServiceItemBasicSchema {
  id: string;
  name: string;
  service_type: string;
  price: number;
  duration_minutes: number;
  is_duration_based: boolean;
}
