/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceFiltersSchemaCommunityId } from './serviceFiltersSchemaCommunityId';
import type { ServiceFiltersSchemaCommunitySlug } from './serviceFiltersSchemaCommunitySlug';
import type { ServiceFiltersSchemaCreatorId } from './serviceFiltersSchemaCreatorId';
import type { ServiceFiltersSchemaIsBroadcasted } from './serviceFiltersSchemaIsBroadcasted';
import type { ServiceFiltersSchemaSearch } from './serviceFiltersSchemaSearch';
import type { ServiceFiltersSchemaServiceType } from './serviceFiltersSchemaServiceType';
import type { ServiceFiltersSchemaStatus } from './serviceFiltersSchemaStatus';

export interface ServiceFiltersSchema {
  search?: ServiceFiltersSchemaSearch;
  community_id?: ServiceFiltersSchemaCommunityId;
  community_slug?: ServiceFiltersSchemaCommunitySlug;
  creator_id?: ServiceFiltersSchemaCreatorId;
  service_type?: ServiceFiltersSchemaServiceType;
  status?: ServiceFiltersSchemaStatus;
  is_broadcasted?: ServiceFiltersSchemaIsBroadcasted;
  page?: number;
  per_page?: number;
}
