/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceAttachmentSchema } from './serviceAttachmentSchema';
import type { ServiceItemSchemaMaxMessagesADay } from './serviceItemSchemaMaxMessagesADay';
import type { ServiceItemSchemaPreviewImage } from './serviceItemSchemaPreviewImage';
import type { ServiceItemSchemaReplyTime } from './serviceItemSchemaReplyTime';
import type { ServiceTypeEnum } from './serviceTypeEnum';

export interface ServiceItemSchema {
  id: string;
  creator_id: number;
  creator_username: string;
  creator_display_name: string;
  community_id: number;
  community_name: string;
  service_type: ServiceTypeEnum;
  name: string;
  description: string;
  price: number;
  duration_minutes: number;
  is_duration_based: boolean;
  status: string;
  is_available: boolean;
  is_broadcasted: boolean;
  preview_image?: ServiceItemSchemaPreviewImage;
  total_purchases: number;
  total_revenue: number;
  created_at: string;
  updated_at: string;
  attachments?: ServiceAttachmentSchema[];
  attachments_required?: boolean;
  max_messages_a_day?: ServiceItemSchemaMaxMessagesADay;
  reply_time?: ServiceItemSchemaReplyTime;
}
