/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { TagItemSchemaDescription } from './tagItemSchemaDescription';

export interface TagItemSchema {
  id: number;
  name: string;
  slug: string;
  description?: TagItemSchemaDescription;
  created_at: string;
  usage_count?: number;
}
