/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export interface TagResponseSchema {
  id: number;
  name: string;
  slug: string;
  usage_count: number;
}
