/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { TagSchemaDescription } from './tagSchemaDescription';

/**
 * Schema for tag representation
 */
export interface TagSchema {
  id: number;
  name: string;
  slug: string;
  description?: TagSchemaDescription;
  usage_count?: number;
}
