/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export interface TextResponseSchema {
  text_value: string;
  response_count: number;
  percentage: number;
  is_correct?: boolean;
}
