/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineFiltersSchemaChatId } from './timelineFiltersSchemaChatId';
import type { TimelineFiltersSchemaCommunityId } from './timelineFiltersSchemaCommunityId';
import type { TimelineFiltersSchemaItemType } from './timelineFiltersSchemaItemType';
import type { TimelineFiltersSchemaSenderId } from './timelineFiltersSchemaSenderId';

export interface TimelineFiltersSchema {
  chat_id?: TimelineFiltersSchemaChatId;
  community_id?: TimelineFiltersSchemaCommunityId;
  sender_id?: TimelineFiltersSchemaSenderId;
  item_type?: TimelineFiltersSchemaItemType;
  include_broadcasts?: boolean;
  page?: number;
  per_page?: number;
}
