/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { MentorDetailsSchema } from './mentorDetailsSchema';
import type { TimelineItemAttachmentSchema } from './timelineItemAttachmentSchema';
import type { TimelineItemSchemaCallDuration } from './timelineItemSchemaCallDuration';
import type { TimelineItemSchemaCallStatus } from './timelineItemSchemaCallStatus';
import type { TimelineItemSchemaChatId } from './timelineItemSchemaChatId';
import type { TimelineItemSchemaCommunityId } from './timelineItemSchemaCommunityId';
import type { TimelineItemSchemaContent } from './timelineItemSchemaContent';
import type { TimelineItemSchemaDeliveredAt } from './timelineItemSchemaDeliveredAt';
import type { TimelineItemSchemaReadAt } from './timelineItemSchemaReadAt';
import type { TimelineItemSchemaServiceItem } from './timelineItemSchemaServiceItem';

export interface TimelineItemSchema {
  id: string;
  chat_id?: TimelineItemSchemaChatId;
  community_id?: TimelineItemSchemaCommunityId;
  sender: MentorDetailsSchema;
  service_item?: TimelineItemSchemaServiceItem;
  item_type: string;
  content?: TimelineItemSchemaContent;
  attachments?: TimelineItemAttachmentSchema[];
  call_duration?: TimelineItemSchemaCallDuration;
  call_status?: TimelineItemSchemaCallStatus;
  is_delivered: boolean;
  is_read: boolean;
  delivered_at?: TimelineItemSchemaDeliveredAt;
  read_at?: TimelineItemSchemaReadAt;
  created_at: string;
  is_broadcast: boolean;
}
