/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { TodoListDetailSchemaPrice } from './todoListDetailSchemaPrice';

/**
 * Schema for todo list details
 */
export interface TodoListDetailSchema {
  id: number;
  folder_id: string;
  slug: string;
  name: string;
  description: string;
  color: string;
  access_level: string;
  access_level_display: string;
  price?: TodoListDetailSchemaPrice;
  is_owner: boolean;
  total_todos: number;
  completed_todos: number;
  completion_percentage: number;
  created_at: string;
  updated_at: string;
}
