/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { ToggleBookmarkResponseSchemaBookmarkId } from './toggleBookmarkResponseSchemaBookmarkId';

/**
 * Response schema for toggling bookmark
 */
export interface ToggleBookmarkResponseSchema {
  bookmarked: boolean;
  message: string;
  bookmark_id?: ToggleBookmarkResponseSchemaBookmarkId;
}
