/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { ToggleBookmarkSchemaFolderId } from './toggleBookmarkSchemaFolderId';
import type { ToggleBookmarkSchemaNotes } from './toggleBookmarkSchemaNotes';

/**
 * Schema for toggling bookmark
 */
export interface ToggleBookmarkSchema {
  folder_id?: ToggleBookmarkSchemaFolderId;
  notes?: ToggleBookmarkSchemaNotes;
}
