/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export interface TransactionSummarySchema {
  total_credits: number;
  total_debits: number;
  current_balance: number;
  total_transactions: number;
  pending_amount: number;
}
