/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { TransactionFiltersSchemaCreditsOnly } from './transactionFiltersSchemaCreditsOnly';
import type { TransactionFiltersSchemaDateFrom } from './transactionFiltersSchemaDateFrom';
import type { TransactionFiltersSchemaDateTo } from './transactionFiltersSchemaDateTo';
import type { TransactionFiltersSchemaDebitsOnly } from './transactionFiltersSchemaDebitsOnly';
import type { TransactionFiltersSchemaMaxAmount } from './transactionFiltersSchemaMaxAmount';
import type { TransactionFiltersSchemaMinAmount } from './transactionFiltersSchemaMinAmount';
import type { TransactionFiltersSchemaPaymentMethod } from './transactionFiltersSchemaPaymentMethod';
import type { TransactionFiltersSchemaSearch } from './transactionFiltersSchemaSearch';
import type { TransactionFiltersSchemaStatus } from './transactionFiltersSchemaStatus';
import type { TransactionFiltersSchemaTransactionType } from './transactionFiltersSchemaTransactionType';

export interface TransactionFiltersSchema {
  transaction_type?: TransactionFiltersSchemaTransactionType;
  status?: TransactionFiltersSchemaStatus;
  min_amount?: TransactionFiltersSchemaMinAmount;
  max_amount?: TransactionFiltersSchemaMaxAmount;
  date_from?: TransactionFiltersSchemaDateFrom;
  date_to?: TransactionFiltersSchemaDateTo;
  payment_method?: TransactionFiltersSchemaPaymentMethod;
  search?: TransactionFiltersSchemaSearch;
  credits_only?: TransactionFiltersSchemaCreditsOnly;
  debits_only?: TransactionFiltersSchemaDebitsOnly;
  page?: number;
  per_page?: number;
  order_by?: string;
}
