/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateServiceSchemaDescription } from './updateServiceSchemaDescription';
import type { UpdateServiceSchemaDurationMinutes } from './updateServiceSchemaDurationMinutes';
import type { UpdateServiceSchemaIsAvailable } from './updateServiceSchemaIsAvailable';
import type { UpdateServiceSchemaIsDurationBased } from './updateServiceSchemaIsDurationBased';
import type { UpdateServiceSchemaName } from './updateServiceSchemaName';
import type { UpdateServiceSchemaPrice } from './updateServiceSchemaPrice';
import type { UpdateServiceSchemaStatus } from './updateServiceSchemaStatus';

export interface UpdateServiceSchema {
  name?: UpdateServiceSchemaName;
  description?: UpdateServiceSchemaDescription;
  price?: UpdateServiceSchemaPrice;
  duration_minutes?: UpdateServiceSchemaDurationMinutes;
  is_duration_based?: UpdateServiceSchemaIsDurationBased;
  status?: UpdateServiceSchemaStatus;
  is_available?: UpdateServiceSchemaIsAvailable;
}
