/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateTimelineItemSchemaCallDuration } from './updateTimelineItemSchemaCallDuration';
import type { UpdateTimelineItemSchemaCallStatus } from './updateTimelineItemSchemaCallStatus';
import type { UpdateTimelineItemSchemaContent } from './updateTimelineItemSchemaContent';
import type { UpdateTimelineItemSchemaIsRead } from './updateTimelineItemSchemaIsRead';

export interface UpdateTimelineItemSchema {
  content?: UpdateTimelineItemSchemaContent;
  is_read?: UpdateTimelineItemSchemaIsRead;
  call_duration?: UpdateTimelineItemSchemaCallDuration;
  call_status?: UpdateTimelineItemSchemaCallStatus;
}
