/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateBookmarkFolderSchemaAccessLevel } from './updateBookmarkFolderSchemaAccessLevel';
import type { UpdateBookmarkFolderSchemaColor } from './updateBookmarkFolderSchemaColor';
import type { UpdateBookmarkFolderSchemaContentType } from './updateBookmarkFolderSchemaContentType';
import type { UpdateBookmarkFolderSchemaDescription } from './updateBookmarkFolderSchemaDescription';
import type { UpdateBookmarkFolderSchemaIsTodoFolder } from './updateBookmarkFolderSchemaIsTodoFolder';
import type { UpdateBookmarkFolderSchemaName } from './updateBookmarkFolderSchemaName';
import type { UpdateBookmarkFolderSchemaPrice } from './updateBookmarkFolderSchemaPrice';

/**
 * Schema for updating bookmark folder
 */
export interface UpdateBookmarkFolderSchema {
  name?: UpdateBookmarkFolderSchemaName;
  description?: UpdateBookmarkFolderSchemaDescription;
  color?: UpdateBookmarkFolderSchemaColor;
  access_level?: UpdateBookmarkFolderSchemaAccessLevel;
  price?: UpdateBookmarkFolderSchemaPrice;
  is_todo_folder?: UpdateBookmarkFolderSchemaIsTodoFolder;
  content_type?: UpdateBookmarkFolderSchemaContentType;
}
