/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keyo API
 * API for Keyo Polls app
 * OpenAPI spec version: 1.0.0
 */

export interface UsernameAvailabilitySchema {
  available: boolean;
  error?: string;
  error_code?: string;
}
